name: Unit Tests
on:
  push:
    branches:
      - github_test
  pull_request:
    branches:
      - main
      - master
jobs:
  rspec:
    runs-on:
      - ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - 2.3
          - 2.2
        docker_version:
          - 5:19.03.8~3-0~ubuntu-bionic
          - 5:18.09.9~3-0~ubuntu-bionic
          - 18.06.3~ce~3-0~ubuntu
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - name: unit tests
        env:
          DOCKER_VERSION: ${{ matrix.docker_version }}
        run: |
          gem install bundler -v '~> 1.17.3'
          bundle update
          sudo ./script/install_docker.sh ${DOCKER_VERSION} ${DOCKER_CE}
          uname -a
          docker --version
          docker info
          bundle exec rake
